id: I8CB49978
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-05-19T10:54:02+00:00'
last_modified: '2022-06-16T05:26:35.916067+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4863
  title: རྒྱལ་བའི་བསྟན་འགྱུར་ལྷ་ས་དཔར་མའི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    9A7C:
      image_group_id: I3CN8643
      title: ''
      total_pages: ''
      order: 1
      base_file: 9A7C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
